### ISSUE TITLE
Adapt for terser v5 and async minification

### ISSUE THREAD

**Issue by nylen** [adascal/grunt-terser#11]
Thanks for making `grunt-terser`!

I copied the code into our project's source tree to be able to manage the version of `terser` there without requiring a duplicated version or other hacks: https://github.com/ClassicPress/ClassicPress/pull/608/commits/ab4909919e66259f9c39ed581d3029e67d6e438e

Here are the changes needed to make `grunt-terser` work asynchronously since [`terser` v5 now returns a `Promise`](https://github.com/terser/terser/blob/v5.1.0/CHANGELOG.md#v500-beta0): https://github.com/ClassicPress/ClassicPress/pull/608/commits/fa59307310e91347c9cb64653ccb8b764cb4569f

**Comment by adascal** [comment]
Thanks for your issue!

I've just released v2 of grunt-terser plugin with terser v5 support
