### ISSUE TITLE
>> SyntaxError: "VARIABLE_NAME" is redeclared

### ISSUE THREAD

**Issue by jawad-aziz-farhad** [adascal/grunt-terser#12]
I have two files where I'm importing a module oracledb. I have defined it in both files as follows:
**const oracledb= require("oracledb");**

when I run grunt terser, I got this error:
>> SyntaxError: "oracledb" is redeclared.

if I change above to (**const to var** ):
**var oracledb= require("oracledb");**
It works.

**Comment by adascal** [comment]
I guess, your show pass custom options to `terser` https://github.com/terser/terser#minify-options

Probably `module: true` should be passed

**Comment by adascal** [comment]
Closing cause inactivity
