### ISSUE TITLE
TypeError: Cannot read property 'resolve_defines' of null

### ISSUE THREAD

**Issue by trainbolt** [adascal/grunt-terser#13]
Hi, I don't have a fully reproducible example at the moment. Hoping someone might see this and know what's going on without having to do that.

Grunt task looks like:
```js
terser: {
  core: {
    options: {
      output: {
        comments: false
      },
      compress: {
        typeofs: false
      },
      mangle: {
        properties: false
      },
      sourceMap: true
    },
    files: {
      'assets/dist/js/core.min.js': 'assets/dist/js/core.js',
      'assets/dist/js/core-extra.min.js': 'assets/dist/js/core-extra.js',
      'assets/dist/js/site.min.js': 'assets/dist/js/site.js'
    }
  }
}
```

Console output says:
```text
Running "terser:core" (terser) task
>> TypeError: Cannot read property 'resolve_defines' of null
>> TypeError: Cannot read property 'resolve_defines' of null
>> 1 grunt.util.pluralize(createdFiles, 'file/files') created.
```

It seems to have run ok, but it's hard to identify if this has caused any issues.

**Comment by karatektus** [comment]
some of your paths are probably wrong. got the same message and forgot a folder in the path. grunt is really annoying that it doesnt just tell you "unknown path" or something

**Comment by adascal** [comment]
Closing it, cause like @karatektus said that issue happen then your paths are invalid and grunt can't resolve it
