### ISSUE TITLE
No Minified Files are Coming Out

### ISSUE THREAD

**Issue by Kelderic** [adascal/grunt-terser#16]
Here there!

I'm switching from grunt-contrib-uglify over to grunt-terser, and for some reason, I'm not getting any files output. Here are some configs I've tried:

```
		terser: {
			scripts : {
				options: {
					compress: {
						drop_console: false
					}
				},
				files: [
					{   expand: true, 
						src: '**/*.js', 
						dest: '<%= assetsPath %>/scripts', 
						cwd: '<%= assetsPath %>/scripts',
						ext: '.min.js'
					}
				]
			}
		},
```

```
		terser: {
			scripts : {
				options: {
					compress: {
						drop_console: false
					}
				},
				files: [
					{   expand: true, 
						src: '**/*.js', 
						dest: '<%= assetsPath %>/scripts', 
						cwd: '<%= assetsPath %>/scripts/min',
					}
				]
			}
		},
````

```
		terser: {
			scripts : {
				options: {
					compress: {
						drop_console: false
					}
				},
				files: {
					'<%= assetsPath %>/scripts/classes.min.js': '<%= assetsPath %>/scripts/classes.js',
				}
			}
		},
```

None of those options work. Am I doing something wrong?

**Comment by Kelderic** [comment]
I've verified that the assetsPath is being correctly filled in, also.

**Comment by adascal** [comment]
Hi @Kelderic, can you create a simple project and reproduce issue?

**Comment by Kelderic** [comment]
I copied the repo, stripped it down, and now I'm getting an error saying that the task "terser" can't be found. I've run out of time for tonight, but I'll keep debugging tomorrow.

**Comment by Kelderic** [comment]
An update: I got a very stripped down version working. I'm trying to slowly change it to match my production environment to see where the break happens. I'm not sure yet if it's a problem in my end, or a bug.

**Comment by Kelderic** [comment]
The issue is a conflict between `grunt-terser` and `grunt-ftpush`. I don't know why, but when I have the following:

````
grunt.loadNpmTasks('grunt-ftpush');
````

Even if it's not being called as part of the task, then nothing comes out of Terser. There are also no warnings.

**Comment by Kelderic** [comment]
Not sure how much it helps, but I started looking through forks, and this fork: https://github.com/miraries/grunt-terser doesn't have the conflict. It works despite the present of ftpush.

**Comment by adascal** [comment]
It would very help if you create a small repo with reproduced issue. I can't reproduce it

**Comment by adascal** [comment]
What `grunt` version are you using? Cause as I can see, `grunt-terser` requires `^1.x` version to support async task, but `grunt-ftpush` is using `~0.4.0`, make sure you are using fresh `grunt` version

**Comment by adascal** [comment]
Closing due inactivity
